### ISSUE TITLE
Specification

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-data#1]
We need a new ganomede module for a pretty basic thing.

Expose a database of JSON documents. Each entry is a single JSON document, with a public endpoints `GET /data/v1/docs/:id`.

There are "apiSecret" protected endpoints to add (`POST /data/v1/docs`), delete (`DELETE /data/v1/docs/:id`) or edit (`POST /data/v1/docs/:id`) a document.

The module can simply be built by proxying requests to CouchDB, or as a thin layer above REDIS, validating API_SECRET for "write" request. I'd just rather not expose the database publicly.

**Comment by elmigranto** [comment]
Do we need to specify IDs on client or is it okay for them to be generated by DB?

**Comment by j3k0** [comment]
We need to be able to specify the ID. But I think both should be possible (if no ID is specified, generate a UUID from code, or let DB do it for you).
