### ISSUE TITLE
CSV import not working properly

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-data#4]
At least on some files... I'll drop an example failing CSV on Skype. The issue might be on ganomede-admin too...

**input CSV columns (examples):**

<img width="123" alt="screen shot 2016-12-09 at 13 48 13" src="https://cloud.githubusercontent.com/assets/191881/21048110/31dbea28-be16-11e6-99d9-202e4f1728c3.png">

<img width="101" alt="screen shot 2016-12-09 at 13 48 02" src="https://cloud.githubusercontent.com/assets/191881/21048112/31e8ea20-be16-11e6-9b61-090b5eede1c9.png">

**output of import:**

<img width="120" alt="screen shot 2016-12-09 at 13 47 45" src="https://cloud.githubusercontent.com/assets/191881/21048140/54d51c2a-be16-11e6-946d-63741c03c6e8.png">
<img width="100" alt="screen shot 2016-12-09 at 13 47 36" src="https://cloud.githubusercontent.com/assets/191881/21048141/54db456e-be16-11e6-8ea7-e921f21ccc85.png">

See words duplicated.

**Some info:**

 * Those columns are imported correctly when put in an individual file...
 * In the big file provided, most columns are OK...
 * The bug is happening identically at each attempt (it's deterministic)

**Comment by elmigranto** [comment]
Those aren't repetitions — there are 2 IDs repeated across 4 columns:
  - `NL:VAKANTIE` (2 columns with this ID);
  - `NL:LANDSCHAP` (2 columns with this ID).

Some words are found in both, so we have "repetitions". So we can:
  1. merge columns with same ID (happening already) and remove duplicates;
  1. throw error (meh).

Doing first one?

**Comment by j3k0** [comment]
Ok, I didn't notice that. I think having 2 columns with the same ID should throw an error. When that happens, there's obviously been a mistake from data entry people.

**Comment by elmigranto** [comment]
Okay. What about duplicate words in a column?

**Comment by j3k0** [comment]
Let it be an error as well, so data entry people clean up their CSVs

**Comment by elmigranto** [comment]
This is admin only, closing in favor of j3k0/ganomede-admin#35.
